# Generated by Django 5.2.3 on 2025-07-03 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userstocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocks',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stocks'),
        ),
        migrations.AlterField(
            model_name='userstocks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
